server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]

  data:
    mongodb:
      uri: ${MONGO_URI}

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: default
      password: ${REDIS_PASSWORD}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  application:
    name: FinTrust-app

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
