server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

#  redis:
#    host: ${SPRING_REDIS_HOST}
#    port: ${SPRING_REDIS_PORT}
#    username: ${SPRING_REDIS_USERNAME}
#    password: ${SPRING_REDIS_PASSWORD}


  application:
    name: secure-vault-app

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
