server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://anshm2674:267414362462@cluster0.v7w7k0t.mongodb.net/securevaultdb?retryWrites=true&w=majority&appName=Cluster0

  redis:
    host: redis-15074.c305.ap-south-1-1.ec2.redns.redis-cloud.com
    port: 15074
    password: N9sWmUXrJX5eQdgV6X41b5sUsMMkKZB1


  application:
    name: FinTrust-app

  mail:
    host: smtp.gmail.com
    port: 587
    username: anshm2674@gmail.com
    password: fsdyuiewvgadtwgu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 2bdb53207998df0733f6523d59cab1a65d5f541ce07b6891507656294ab7ce87
